### ISSUE TITLE
README.md Typo

### ISSUE THREAD

**Issue by tiffanyhe** [Spiderpig86/coronavirus-us-api#12]
**Describe the bug**

<img width="838" alt="Screen Shot 2021-07-05 at 12 01 28 AM" src="https://user-images.githubusercontent.com/30251059/124430847-867f8f80-dd24-11eb-80cc-384ae4d049ea.png">

Instead of "static", it should be "statistic".  :)

**Comment by Spiderpig86** [comment]
Thanks for the report! I have fixed that and a few other issues in the README in commit 5d9e5766a8a374819c2f6d80490315d3ed23ef22.
