### ISSUE TITLE
503 Application Error

### ISSUE THREAD

**Issue by christorepl** [Spiderpig86/coronavirus-us-api#6]
Requests without an API key tell me it's missing the API key, and requests with a key result in a 503 Application Error message. My little apps that use this API are broken!

**Comment by Spiderpig86** [comment]
Thanks for the report. I have rolled back the deployment to the previous version and it is now up again. Seems that one of our security updates broke on Heroku but didn't show any signs of failure in our pipeline. Commit: ad238390a2c10488cc8af9a38d0fd9068f9bda7c I'll have to see why the deployment causes it to fail.

**Comment by Spiderpig86** [comment]
Related: https://github.com/aio-libs/aiohttp/issues/5107

**Comment by Spiderpig86** [comment]
Officially fixed with 882f1d3f5e1901ed254e86db769f89d01f32ab81.
